### ISSUE TITLE
Trying to get property 'accessToken' of non-object

### ISSUE THREAD

**Issue by PHLAK** [beyondcode/forge-cli#8]
Attempting to log in to Forge for the first time and getting an error.

```
$ forge login

 What is your Laravel Forge email?:
 > me@example.com

 What is your password?:
 > 

Logging in...

In LoginCommand.php line 82:
                                                      
  Trying to get property 'accessToken' of non-object
```

I suspect this may be due to having 2FA enabled (it's never prompted for) but haven't dug into the code. Is it possible to set an API key directly without my password (and 2FA code)?

**Comment by mpociot** [comment]
Ah right, it must be 2FA.

Yeah you can create a file called `~/.forge/config.php` with the content:

```php
<?php

return [
'token' => 'YOUR-TOKEN-GOES-HERE',
];
```

**Comment by PHLAK** [comment]
Just dug into the code and found that. Looks like it's working after adding the token manually, thanks!

```
$ forge login
You are already logged in
```
